## Importation des bibliothèques nécessaires et initialiser du dataframee

In [1]:
import whisper
import pandas as pd
import os

In [2]:
# Chemin vers le fichier vidéo à tester (place une vidéo dans le dossier "data/videos")
video_folder = "../data/videos/"

In [4]:
import os
import subprocess

# Chemin vers le dossier contenant les vidéos
video_folder = "../data/videos/"
output_video_folder = "../data/videos_compressed/"

# Créer le dossier de sortie si nécessaire
if not os.path.exists(output_video_folder):
    os.makedirs(output_video_folder)

# Fonction pour compresser une vidéo avec FFmpeg
def compress_video(input_path, output_path):
    command = [
        "ffmpeg", "-i", input_path,
        "-vcodec", "libx264",
        "-crf", "28",  # Ajuste la qualité ici si nécessaire
        "-preset", "fast",
        "-acodec", "aac", "-strict", "-2",
        output_path
    ]
    subprocess.run(command)

# Parcourir toutes les vidéos dans le dossier
for video_file in os.listdir(video_folder):
    if video_file.endswith(('.mp4', '.avi', '.mov', '.mkv','MOV')):  # Filtrer les formats vidéo
        input_video_path = os.path.join(video_folder, video_file)
        output_video_path = os.path.join(output_video_folder, video_file)

        print(f"Compression de {video_file}...")
        compress_video(input_video_path, output_video_path)

print("Compression terminée.")

Compression de BETHOUX_camille.mp4...

ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/videos/BETHOUX_camille.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
  Duration: 00:00:37.76, start: 0.000000, bitrate: 1504 kb/s
  Stream #0:0[0x1](und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 848x480, 1439 kb/s, 29.95 fps, 30 tbr, 600 tbn (default)
      Metadata:
        vendor_id       : [0][0][0][0]
      Side data:
        displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 62 kb/s (default)
      Metadata:
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x152815a60] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x152815a60] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x152815a60] 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '../data/videos_compressed/BETHOUX_camille.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    encoder         : Lavf61.7.100
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 480x848, q=2-31, 30 fps, 15360 tbn (default)
      Metadata:
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 libx264
      Side data:
        cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 aac
[out#0/mp4 @ 0x152814cc0] video:2124KiB audio:597KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 1.509998%
frame= 1130 fps=267 q=-1.0 Lsize=    2763KiB time=00:00:37.66 bitrate= 600.8kbits/s speed= 8.9x
[libx264 @ 0x152815a60] frame I:5     Avg QP:25.43  size:  9656
[libx264 @ 0x152815a60] frame P:327   Avg QP:27.58  size:  3777
[libx264 @ 0x152815a60] frame B:798   Avg QP:29.49  size:  1117
[libx264 @ 0x152815a60] consecutive B-frames:  4.2%  2.8%  5.8% 87.1%
[libx264 @ 0x152815a60] mb I  I16..4: 35.7% 55.4%  8.9%
[libx264 @ 0x152815a60] mb P  I16..4:  8.0%  8.4%  0.6%  P16..4: 38.9%  7.7%  2.5%  0.0%  0.0%    skip:33.9%
[libx264 @ 0x152815a60] mb B  I16..4:  1.7%  2.0%  0.0%  B16..8: 20.7%  2.7%  0.1%  direct: 3.7%  skip:69.0%  L0:43.7% L1:51.4% BI: 4.9%
[libx264 @ 0x152815a60] 8x8 transform intra:51.3% inter:79.0%
[libx264 @ 0x152815a60] coded y,uvDC,uvAC intra: 23.6% 34.1% 4.6% inter: 4.6% 5.1% 0.0%
[libx264 @ 0x152815a60] i16 v,h,dc,p: 30% 19% 16% 35%
[libx264 @ 0x152815a60] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 14% 32%  5%  5%  5%  5%  7%  4%
[libx264 @ 0x152815a60] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 13% 21%  6%  7%  8%  6%  7%  3%
[libx264 @ 0x152815a60] i8c dc,h,v,p: 65% 14% 18%  3%
[libx264 @ 0x152815a60] Weighted P-Frames: Y:1.2% UV:0.0%
[libx264 @ 0x152815a60] ref P L0: 68.8% 31.2%
[libx264 @ 0x152815a60] ref B L0: 85.7% 14.3%
[libx264 @ 0x152815a60] ref B L1: 96.5%  3.5%
[libx264 @ 0x152815a60] kb/s:461.04
[aac @ 0x151f1ae80] Qavg: 823.373
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/videos/MICHEL_Bernard.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2024-10-24T21:15:07.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 6.182387
    com.apple.quicktime.location.ISO6709: +33.9892-006.8193+087.123/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone SE (3rd generation)
    com.apple.quicktime.software: 17.6.1
    com.apple.quicktime.creationdate: 2024-10-24T22:15:07+0100
  Duration: 00:00:33.93, start: 0.000000, bitrate: 15587 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 15334 kb/s, 29.97 fps, 29.97 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2024-10-24T21:15:07.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : H.264
      Side data:
        displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 166 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T21:15:07.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T21:15:07.000000Z
        handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 23 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T21:15:07.000000Z
        handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 49 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T21:15:07.000000Z
        handler_name    : Core Media Metadata
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x14511b880] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x14511b880] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 0x14511b880] 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mov, to '../data/videos_compressed/MICHEL_Bernard.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    com.apple.quicktime.creationdate: 2024-10-24T22:15:07+0100
    com.apple.quicktime.location.accuracy.horizontal: 6.182387
    com.apple.quicktime.location.ISO6709: +33.9892-006.8193+087.123/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone SE (3rd generation)
    com.apple.quicktime.software: 17.6.1
    encoder         : Lavf61.7.100
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1080x1920, q=2-31, 29.97 fps, 30k tbn (default)
      Metadata:
        creation_time   : 2024-10-24T21:15:07.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 libx264
      Side data:
        cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T21:15:07.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 aac

Compression de MICHEL_Bernard.MOV...

[out#0/mov @ 0x14511abc0] video:4845KiB audio:547KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.694439%
frame= 1017 fps= 61 q=-1.0 Lsize=    5429KiB time=00:00:33.86 bitrate=1313.2kbits/s speed=2.02x
[libx264 @ 0x14511b880] frame I:6     Avg QP:26.05  size: 41712
[libx264 @ 0x14511b880] frame P:258   Avg QP:27.28  size:  8883
[libx264 @ 0x14511b880] frame B:753   Avg QP:28.42  size:  3211
[libx264 @ 0x14511b880] consecutive B-frames:  0.8%  1.2%  0.9% 97.1%
[libx264 @ 0x14511b880] mb I  I16..4: 32.5% 60.7%  6.8%
[libx264 @ 0x14511b880] mb P  I16..4:  5.0%  4.9%  0.1%  P16..4: 25.9%  2.8%  1.6%  0.0%  0.0%    skip:59.7%
[libx264 @ 0x14511b880] mb B  I16..4:  1.7%  1.8%  0.0%  B16..8:  8.8%  0.7%  0.0%  direct: 5.4%  skip:81.6%  L0:43.3% L1:55.1% BI: 1.6%
[libx264 @ 0x14511b880] 8x8 transform intra:51.0% inter:89.4%
[libx264 @ 0x14511b880] coded y,uvDC,uvAC intra: 15.6% 39.4% 2.5% inter: 2.7% 6.5% 0.0%
[libx264 @ 0x14511b880] i16 v,h,dc,p: 40% 25% 16% 20%
[libx264 @ 0x14511b880] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 14% 12% 57%  3%  4%  3%  3%  3%  2%
[libx264 @ 0x14511b880] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 19% 19%  6%  7%  7%  6%  5%  4%
[libx264 @ 0x14511b880] i8c dc,h,v,p: 60% 18% 20%  2%
[libx264 @ 0x14511b880] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x14511b880] ref P L0: 57.7% 42.3%
[libx264 @ 0x14511b880] ref B L0: 75.1% 24.9%
[libx264 @ 0x14511b880] ref B L1: 93.6%  6.4%
[libx264 @ 0x14511b880] kb/s:1169.39
[aac @ 0x14516d610] Qavg: 708.172

Compression de BARTOZZI_Mathieu.MOV...

ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/videos/BARTOZZI_Mathieu.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2024-10-24T20:54:50.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 45.039206
    com.apple.quicktime.location.ISO6709: +33.9892-006.8197+090.432/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone SE (3rd generation)
    com.apple.quicktime.software: 17.6.1
    com.apple.quicktime.creationdate: 2024-10-24T21:54:50+0100
  Duration: 00:00:51.15, start: 0.000000, bitrate: 15621 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 15365 kb/s, 29.97 fps, 29.97 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2024-10-24T20:54:50.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : H.264
      Side data:
        displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 168 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T20:54:50.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T20:54:50.000000Z
        handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 23 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T20:54:50.000000Z
        handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 49 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T20:54:50.000000Z
        handler_name    : Core Media Metadata
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x141f13010] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x141f13010] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 0x141f13010] 264 - core 164 r3108 31e19f9 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mov, to '../data/videos_compressed/BARTOZZI_Mathieu.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    com.apple.quicktime.creationdate: 2024-10-24T21:54:50+0100
    com.apple.quicktime.location.accuracy.horizontal: 45.039206
    com.apple.quicktime.location.ISO6709: +33.9892-006.8197+090.432/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone SE (3rd generation)
    com.apple.quicktime.software: 17.6.1
    encoder         : Lavf61.7.100
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1080x1920, q=2-31, 29.97 fps, 30k tbn (default)
      Metadata:
        creation_time   : 2024-10-24T20:54:50.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 libx264
      Side data:
        cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        creation_time   : 2024-10-24T20:54:50.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 aac
[out#0/mov @ 0x14290d3e0] video:11320KiB audio:819KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.458730%
frame= 1533 fps= 49 q=-1.0 Lsize=   12194KiB time=00:00:51.08 bitrate=1955.5kbits/s speed=1.63x
[libx264 @ 0x141f13010] frame I:10    Avg QP:26.20  size: 37567
[libx264 @ 0x141f13010] frame P:387   Avg QP:27.81  size: 12649
[libx264 @ 0x141f13010] frame B:1136  Avg QP:29.13  size:  5563
[libx264 @ 0x141f13010] consecutive B-frames:  1.0%  0.4%  0.8% 97.8%
[libx264 @ 0x141f13010] mb I  I16..4: 33.9% 60.6%  5.6%
[libx264 @ 0x141f13010] mb P  I16..4:  8.4%  9.4%  0.2%  P16..4: 30.6%  3.7%  1.8%  0.0%  0.0%    skip:45.9%
[libx264 @ 0x141f13010] mb B  I16..4:  3.0%  4.2%  0.0%  B16..8: 13.3%  1.3%  0.0%  direct: 8.5%  skip:69.7%  L0:45.4% L1:52.7% BI: 1.9%
[libx264 @ 0x141f13010] 8x8 transform intra:55.9% inter:88.9%
[libx264 @ 0x141f13010] coded y,uvDC,uvAC intra: 18.0% 40.8% 2.4% inter: 4.2% 10.0% 0.0%
[libx264 @ 0x141f13010] i16 v,h,dc,p: 33% 26% 15% 26%
[libx264 @ 0x141f13010] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 17% 13% 49%  3%  5%  4%  4%  4%  3%
[libx264 @ 0x141f13010] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 18% 20%  6%  7%  7%  6%  5%  3%
[libx264 @ 0x141f13010] i8c dc,h,v,p: 62% 18% 17%  2%
[libx264 @ 0x141f13010] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x141f13010] ref P L0: 58.6% 41.4%
[libx264 @ 0x141f13010] ref B L0: 78.3% 21.7%
[libx264 @ 0x141f13010] ref B L1: 94.0%  6.0%
[libx264 @ 0x141f13010] kb/s:1812.76
[aac @ 0x141e21c40] Qavg: 626.299

Compression terminée.

In [5]:
# Fonction pour extraire les noms et prénoms à partir des fichiers vidéos

def extract_names_from_videos(video_folder):
    video_files = [f for f in os.listdir(video_folder) if f.endswith(('.mp4', '.avi', '.mov', 'MOV'))]

    # Séparer le nom et le prénom en supposant que le format est "NOM_prénom.xxx"
    data = []
    for video in video_files:
        base_name = os.path.splitext(video)[0]  # Enlever l'extension (.mp4, .avi, etc.)
        if '_' in base_name:
            nom, prenom = base_name.split('_', 1)  # Séparer sur le premier '_'
        else:
            nom, prenom = base_name, ''  # Si pas de '_', mettre prénom vide

        data.append({'video_file': video, 'nom': nom, 'prénom': prenom})

    # Créer un DataFrame
    df_videos = pd.DataFrame(data)
    return df_videos

df_videos=extract_names_from_videos(output_video_folder)

## Extraction du transcript

In [7]:
# Spécifie le modèle Whisper à utiliser
whisper_model_name = "base"  # Par exemple, "tiny", "base", "small", "medium", ou "large"
whisper_model = whisper.load_model(whisper_model_name)

/Users/mathieubartozzi/.pyenv/versions/3.10.6/envs/video_auto_rating/lib/python3.10/site-packages/whisper/__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)

In [8]:
# Fonction pour transcrire une vidéo avec Whisper
def transcribe_video(whisper_model, video_path):
    result = whisper_model.transcribe(video_path)
    return result['text']

# Ajouter une colonne 'transcript' avec les transcriptions de chaque vidéo
df_videos['transcript'] = df_videos['video_file'].apply(
    lambda video_file: transcribe_video(whisper_model, os.path.join(output_video_folder, video_file))
)

/Users/mathieubartozzi/.pyenv/versions/3.10.6/envs/video_auto_rating/lib/python3.10/site-packages/whisper/transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
/Users/mathieubartozzi/.pyenv/versions/3.10.6/envs/video_auto_rating/lib/python3.10/site-packages/whisper/transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
/Users/mathieubartozzi/.pyenv/versions/3.10.6/envs/video_auto_rating/lib/python3.10/site-packages/whisper/transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

In [9]:
df_videos.head(5)

,video_file,nom,prénom,transcript
0,BETHOUX_camille.mp4,BETHOUX,camille,"Bonjour, je vais répondre à l'offre de Simnac..."
1,MICHEL_Bernard.MOV,MICHEL,Bernard,"Bonjour, je suis Ravi de postuler pour le pos..."
2,BARTOZZI_Mathieu.MOV,BARTOZZI,Mathieu,"Bonjour, je suis rapide de répondre à l'offre..."

## Analyse non-verbale avec Mediapipe

In [11]:
import cv2
import mediapipe as mp

# Initialiser Mediapipe Pose
mp_pose = mp.solutions.pose
pose = mp_pose.Pose()

# Initialiser Mediapipe Drawing pour dessiner les repères sur l'image
mp_drawing = mp.solutions.drawing_utils

I0000 00:00:1729805443.280193 3449091 gl_context.cc:357] GL version: 2.1 (2.1 Metal - 88.1), renderer: Apple M1

W0000 00:00:1729805443.414894 3453969 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1729805443.432829 3453970 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

In [12]:
# # Fonction pour analyser une vidéo et extraire les informations non-verbales
# def analyze_video(video_path):
#     cap = cv2.VideoCapture(video_path)  # Ouvrir la vidéo
#     pose_data = []  # Stocker les résultats

#     while cap.isOpened():
#         ret, frame = cap.read()
#         if not ret:
#             break  # Fin de la vidéo

#         # Convertir l'image en format RGB pour Mediapipe
#         rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

#         # Obtenir les résultats de pose
#         results = pose.process(rgb_frame)

#         # Vérifier si des poses sont détectées
#         if results.pose_landmarks:
#             landmarks = results.pose_landmarks.landmark
#             pose_data.append(landmarks)

#             # Dessiner les landmarks de la pose sur l'image (facultatif pour visualisation)
#             mp_drawing.draw_landmarks(frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)

#     cap.release()
#     return pose_data  # Retourner les informations de pose


# # Exemple pour ajouter les données de posture dans le DataFrame
# df_videos['pose_data'] = df_videos['video_file'].apply(
#     lambda video_file: analyze_video(os.path.join(video_folder, video_file))
# )

# Key landmarks avec les noms associés et leurs indices
key_landmarks = {
    'left_wrist': 15,
    'right_wrist': 16,
    'left_elbow': 13,
    'right_elbow': 14,
    'left_shoulder': 11,
    'right_shoulder': 12
}

# Fonction pour analyser une vidéo et extraire les key landmarks
def analyze_video_key_landmarks(video_path):
    cap = cv2.VideoCapture(video_path)  # Ouvrir la vidéo
    pose_data = []  # Stocker les résultats des key landmarks

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break  # Fin de la vidéo

        # Convertir l'image en format RGB pour Mediapipe
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Obtenir les résultats de pose
        results = pose.process(rgb_frame)

        # Vérifier si des poses sont détectées
        if results.pose_landmarks:
            landmarks = results.pose_landmarks.landmark

            # Extraire uniquement les key landmarks
            key_landmarks_data = {
                name: (landmarks[idx].x, landmarks[idx].y, landmarks[idx].visibility)
                for name, idx in key_landmarks.items()
            }
            pose_data.append(key_landmarks_data)

            # Facultatif : Dessiner les landmarks de la pose sur l'image pour visualisation
            mp_drawing.draw_landmarks(frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)

    cap.release()
    return pose_data  # Retourner les informations des key landmarks


# Exemple pour ajouter les données de posture (key landmarks) dans le DataFrame
df_videos['pose_data'] = df_videos['video_file'].apply(
    lambda video_file: analyze_video_key_landmarks(os.path.join(output_video_folder, video_file))
)

W0000 00:00:1729805448.132639 3453973 landmark_projection_calculator.cc:186] Using NORM_RECT without IMAGE_DIMENSIONS is only supported for the square ROI. Provide IMAGE_DIMENSIONS or use PROJECTION_MATRIX.
/Users/mathieubartozzi/.pyenv/versions/3.10.6/envs/video_auto_rating/lib/python3.10/site-packages/google/protobuf/symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '

In [13]:
import numpy as np

# Landmarks clés à surveiller (poignets, coudes, épaules)
key_landmarks = {
    'left_wrist': 'left_wrist',
    'right_wrist': 'right_wrist',
    'left_elbow': 'left_elbow',
    'right_elbow': 'right_elbow',
    'left_shoulder': 'left_shoulder',
    'right_shoulder': 'right_shoulder'
}

# Fonction pour calculer les mouvements et la visibilité moyenne à partir de pose_data
def calculate_movement_and_visibility(pose_data, key_landmarks):
    total_movement = {landmark: 0 for landmark in key_landmarks}  # Accumulateur de mouvements
    visibility_stats = {landmark: [] for landmark in key_landmarks}  # Historique de visibilité

    for i in range(1, len(pose_data)):  # Parcourir chaque frame
        previous_frame = pose_data[i - 1]
        current_frame = pose_data[i]

        for landmark_name in key_landmarks:  # Parcourir les key landmarks
            # Récupérer les données des landmarks sur deux frames successives
            prev_landmark = previous_frame[landmark_name]
            curr_landmark = current_frame[landmark_name]

            # Utiliser les attributs x, y, z, visibility
            if prev_landmark[2] > 0.5 and curr_landmark[2] > 0.5:  # Seulement si bien visible
                dist = np.sqrt(
                    (curr_landmark[0] - prev_landmark[0])**2 +
                    (curr_landmark[1] - prev_landmark[1])**2 +
                    (curr_landmark[2] - prev_landmark[2])**2
                )
                total_movement[landmark_name] += dist

            # Enregistrer la visibilité
            visibility_stats[landmark_name].append(curr_landmark[2])  # Visibilité est le 3ème élément

    # Calcul des scores de visibilité moyens
    avg_visibility = {landmark: np.mean(visibility_stats[landmark]) for landmark in visibility_stats}

    return total_movement, avg_visibility

# Appliquer la fonction à toutes les vidéos de la colonne pose_data
df_videos['movements'], df_videos['visibilities'] = zip(*df_videos['pose_data'].apply(
    lambda pose_data: calculate_movement_and_visibility(pose_data, key_landmarks)
))

In [14]:
df_videos.head(5)

,video_file,nom,prénom,transcript,pose_data,movements,visibilities
0,BETHOUX_camille.mp4,BETHOUX,camille,"Bonjour, je vais répondre à l'offre de Simnac...","[{'left_wrist': (1.0578941106796265, 1.1902699...","{'left_wrist': 14.291328720337946, 'right_wris...","{'left_wrist': 0.7811209785333769, 'right_wris..."
1,MICHEL_Bernard.MOV,MICHEL,Bernard,"Bonjour, je suis Ravi de postuler pour le pos...","[{'left_wrist': (0.9465816617012024, 0.9347741...","{'left_wrist': 6.314228394392659, 'right_wrist...","{'left_wrist': 0.4683238630454371, 'right_wris..."
2,BARTOZZI_Mathieu.MOV,BARTOZZI,Mathieu,"Bonjour, je suis rapide de répondre à l'offre...","[{'left_wrist': (0.43789562582969666, 0.971584...","{'left_wrist': 26.5384105406569, 'right_wrist'...","{'left_wrist': 0.8951871749548626, 'right_wris..."

## Mesurer le débit de parole

In [15]:
import cv2

# Fonction pour calculer la durée d'une vidéo en minutes
def get_video_duration(video_path):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return 0
    fps = cap.get(cv2.CAP_PROP_FPS)  # Taux de frames par seconde
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))  # Nombre total de frames
    duration_seconds = frame_count / fps  # Durée en secondes
    cap.release()
    return duration_seconds / 60  # Convertir en minutes

# Fonction pour compter les mots dans une transcription
def count_words(transcript):
    return len(transcript.split())

# Calculer le débit de parole (mots par minute)
def calculate_speech_rate(transcript, video_duration_minutes):
    word_count = count_words(transcript)
    if video_duration_minutes > 0:
        return word_count / video_duration_minutes  # Mots par minute
    else:
        return 0

# Ajouter une colonne 'speech_rate' avec le débit de parole
df_videos['speech_rate'] = df_videos.apply(
    lambda row: calculate_speech_rate(row['transcript'], get_video_duration(os.path.join(video_folder, row['video_file']))),
    axis=1
)

In [16]:
df_videos.head(5)

,video_file,nom,prénom,transcript,pose_data,movements,visibilities,speech_rate
0,BETHOUX_camille.mp4,BETHOUX,camille,"Bonjour, je vais répondre à l'offre de Simnac...","[{'left_wrist': (1.0578941106796265, 1.1902699...","{'left_wrist': 14.291328720337946, 'right_wris...","{'left_wrist': 0.7811209785333769, 'right_wris...",130.388693
1,MICHEL_Bernard.MOV,MICHEL,Bernard,"Bonjour, je suis Ravi de postuler pour le pos...","[{'left_wrist': (0.9465816617012024, 0.9347741...","{'left_wrist': 6.314228394392659, 'right_wrist...","{'left_wrist': 0.4683238630454371, 'right_wris...",141.446884
2,BARTOZZI_Mathieu.MOV,BARTOZZI,Mathieu,"Bonjour, je suis rapide de répondre à l'offre...","[{'left_wrist': (0.43789562582969666, 0.971584...","{'left_wrist': 26.5384105406569, 'right_wrist'...","{'left_wrist': 0.8951871749548626, 'right_wris...",159.520396

## Mesure du ton

In [17]:
import subprocess
import librosa
import numpy as np

audio_folder = "../data/audios"


# Fonction pour extraire l'audio d'une vidéo et l'enregistrer dans le dossier audios
def extract_audio(video_path, output_audio_path):
    command = f"ffmpeg -i {video_path} -q:a 0 -map a {output_audio_path} -y"
    subprocess.call(command, shell=True)

In [18]:
def analyze_pitch_variation(audio_path):
    # Charger l'audio avec Librosa
    y, sr = librosa.load(audio_path)

    # Ajuster la taille de la fenêtre et le hop_length
    frame_length = 1024  # Taille de la fenêtre d'analyse (réduite pour s'adapter)
    hop_length = 256      # Intervalle entre deux analyses de pitch (réduit pour plus de finesse)

    # Utiliser pyin pour extraire la fréquence fondamentale (pitch)
    pitches, voiced_flag, voiced_probs = librosa.pyin(
        y, fmin=librosa.note_to_hz('C2'), fmax=librosa.note_to_hz('C7'), sr=sr, frame_length=frame_length, hop_length=hop_length
    )

    # Ne garder que les pitchs valides (voiced_flag = True)
    valid_pitches = pitches[~np.isnan(pitches)]

    if len(valid_pitches) == 0:
        return 0, 0  # Retourne 0 si aucun pitch n'est détecté

    # Calculer l'écart-type du pitch sur toute la vidéo
    pitch_mean = np.mean(valid_pitches)
    pitch_std = np.std(valid_pitches)

    return pitch_mean, pitch_std

In [19]:

# Ajouter une nouvelle colonne 'audio_file' en modifiant uniquement cette colonne
df_videos['audio_file'] = df_videos['video_file'].apply(
    lambda video_file: video_file.replace('.mp4', '.wav')  # Exemple : remplacer l'extension .mp4 par .wav
)

# Extraire l'audio pour chaque vidéo et l'enregistrer dans le dossier audios
for video_file, audio_file in zip(df_videos['video_file'], df_videos['audio_file']):
    extract_audio(os.path.join(output_video_folder, video_file), os.path.join(audio_folder, audio_file))


# Analyser les variations de pitch après l'extraction audio
df_videos['pitch_mean'], df_videos['pitch_std'] = zip(*df_videos['audio_file'].apply(
    lambda audio_file: analyze_pitch_variation(os.path.join(audio_folder, audio_file))
))

ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/videos_compressed/BETHOUX_camille.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.7.100
  Duration: 00:00:37.76, start: 0.000000, bitrate: 599 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 480x848, 461 kb/s, 29.95 fps, 30 tbr, 15360 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 129 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '../data/audios/BETHOUX_camille.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    ISFT            : Lavf61.7.100
  Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 pcm_s16le
[out#0/wav @ 0x12c005a60] video:0KiB audio:6504KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.001171%
size=    6504KiB time=00:00:37.75 bitrate=1411.2kbits/s speed=1.26e+03x
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/videos_compressed/MICHEL_Bernard.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 512
    compatible_brands: qt
    encoder         : Lavf61.7.100
  Duration: 00:00:33.95, start: 0.000000, bitrate: 1310 kb/s
  Stream #0:0[0x1]: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1080x1920, 1169 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
      Metadata:
        handler_name    : Core Media Video
        vendor_id       : FFMP
        encoder         : Lavc61.19.100 libx264
  Stream #0:1[0x2]: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 131 kb/s (default)
      Metadata:
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mov, to '../data/audios/MICHEL_Bernard.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 512
    compatible_brands: qt
    encoder         : Lavf61.7.100
  Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 aac
[out#0/mov @ 0x131f0ae40] video:0KiB audio:572KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 1.144446%
size=     579KiB time=00:00:33.94 bitrate= 139.6kbits/s speed=74.4x
[aac @ 0x131e1d350] Qavg: 120.000
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../data/videos_compressed/BARTOZZI_Mathieu.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 512
    compatible_brands: qt
    encoder         : Lavf61.7.100
  Duration: 00:00:51.15, start: 0.000000, bitrate: 1952 kb/s
  Stream #0:0[0x1]: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1080x1920, 1812 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
      Metadata:
        handler_name    : Core Media Video
        vendor_id       : FFMP
        encoder         : Lavc61.19.100 libx264
  Stream #0:1[0x2]: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 131 kb/s (default)
      Metadata:
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mov, to '../data/audios/BARTOZZI_Mathieu.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 512
    compatible_brands: qt
    encoder         : Lavf61.7.100
  Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
      Metadata:
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 aac
[out#0/mov @ 0x13ae20260] video:0KiB audio:864KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 1.092844%
size=     873KiB time=00:00:51.15 bitrate= 139.9kbits/s speed=74.3x
[aac @ 0x13ae21130] Qavg: 120.000
/var/folders/p9/_030_tzn0cx_x11mkmfz6w800000gn/T/ipykernel_20363/3601006044.py:3: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(audio_path)
/Users/mathieubartozzi/.pyenv/versions/3.10.6/envs/video_auto_rating/lib/python3.10/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

In [178]:
# import numpy as np

# # Landmarks clés à surveiller (poignets, coudes, épaules)
# key_landmarks = {
#     'left_wrist': 15,
#     'right_wrist': 16,
#     'left_elbow': 13,
#     'right_elbow': 14,
#     'left_shoulder': 11,
#     'right_shoulder': 12
# }

# # Fonction pour calculer les mouvements et la visibilité moyenne à partir de pose_data
# def calculate_movement_and_visibility(pose_data, key_landmarks):
#     total_movement = {landmark: 0 for landmark in key_landmarks}  # Accumulateur de mouvements
#     visibility_stats = {landmark: [] for landmark in key_landmarks}  # Historique de visibilité

#     for i in range(1, len(pose_data)):  # Parcourir chaque frame
#         previous_frame = pose_data[i - 1]
#         current_frame = pose_data[i]

#         for landmark_name, landmark_index in key_landmarks.items():
#             # Récupérer les données des landmarks sur deux frames successives
#             prev_landmark = previous_frame[landmark_index]
#             curr_landmark = current_frame[landmark_index]

#             # Utiliser les attributs des objets NormalizedLandmark
#             if prev_landmark.visibility > 0.5 and curr_landmark.visibility > 0.5:  # Seulement si bien visible
#                 dist = np.sqrt(
#                     (curr_landmark.x - prev_landmark.x)**2 +
#                     (curr_landmark.y - prev_landmark.y)**2 +
#                     (curr_landmark.z - prev_landmark.z)**2
#                 )
#                 total_movement[landmark_name] += dist

#             # Enregistrer la visibilité
#             visibility_stats[landmark_name].append(curr_landmark.visibility)

#     # Calcul des scores de visibilité moyens
#     avg_visibility = {landmark: np.mean(visibility_stats[landmark]) for landmark in visibility_stats}

#     return total_movement, avg_visibility

# # Appliquer la fonction à toutes les vidéos de la colonne pose_data
# df_videos['movements'], df_videos['visibilities'] = zip(*df_videos['pose_data'].apply(
#     lambda pose_data: calculate_movement_and_visibility(pose_data, key_landmarks)
# ))

In [20]:
df_videos

,video_file,nom,prénom,transcript,pose_data,movements,visibilities,speech_rate,audio_file,pitch_mean,pitch_std
0,BETHOUX_camille.mp4,BETHOUX,camille,"Bonjour, je vais répondre à l'offre de Simnac...","[{'left_wrist': (1.0578941106796265, 1.1902699...","{'left_wrist': 14.291328720337946, 'right_wris...","{'left_wrist': 0.7811209785333769, 'right_wris...",130.388693,BETHOUX_camille.wav,204.134598,28.292133
1,MICHEL_Bernard.MOV,MICHEL,Bernard,"Bonjour, je suis Ravi de postuler pour le pos...","[{'left_wrist': (0.9465816617012024, 0.9347741...","{'left_wrist': 6.314228394392659, 'right_wrist...","{'left_wrist': 0.4683238630454371, 'right_wris...",141.446884,MICHEL_Bernard.MOV,106.698208,23.543169
2,BARTOZZI_Mathieu.MOV,BARTOZZI,Mathieu,"Bonjour, je suis rapide de répondre à l'offre...","[{'left_wrist': (0.43789562582969666, 0.971584...","{'left_wrist': 26.5384105406569, 'right_wrist'...","{'left_wrist': 0.8951871749548626, 'right_wris...",159.520396,BARTOZZI_Mathieu.MOV,131.136697,33.770491

## Calcul des scores globaux

### Score de communication non verbale

In [21]:
from sklearn.preprocessing import MinMaxScaler

# utilisation de MinMaxScaler
scaler = MinMaxScaler()

#Création du  DataFrame df_score avec les colonnes 'nom' et 'prénom'
df_score = df_videos[['nom', 'prénom']]

In [22]:
from sklearn.preprocessing import MinMaxScaler

# Fonction pour calculer le score basé sur les mouvements et la visibilité
def calculate_movement_rate(total_movement, avg_visibility):
    # Pondérations des différents critères (ajustables selon tes besoins)
    stability_weight = 0.3
    gesture_weight = 0.5
    diversity_weight = 0.2

    # 1. Stabilité posturale : Basé sur la visibilité des épaules
    stability_score = (avg_visibility['left_shoulder'] + avg_visibility['right_shoulder']) / 2

    # 2. Dynamique gestuelle : Basé sur le mouvement des poignets et coudes
    gesture_score = (total_movement['left_wrist'] + total_movement['right_wrist'] +
                     total_movement['left_elbow'] + total_movement['right_elbow']) / 4

    # 3. Diversité des gestes : Basé sur la différence entre les mouvements des deux côtés du corps
    left_side_movement = total_movement['left_wrist'] + total_movement['left_elbow']
    right_side_movement = total_movement['right_wrist'] + total_movement['right_elbow']

    # Calcul de la diversité : si les deux côtés sont équilibrés en termes de mouvements
    if max(left_side_movement, right_side_movement) > 0:
        diversity_score = min(left_side_movement, right_side_movement) / max(left_side_movement, right_side_movement)
    else:
        diversity_score = 0

    # Calcul du score lié au mouvement en pondérant les critères
    movement_rate = (stability_score * stability_weight +
                     gesture_score * gesture_weight +
                     diversity_score * diversity_weight)

    return movement_rate


# Calculer les scores de movement_rate
df_score['movement_rate'] = df_videos.apply(
    lambda row: calculate_movement_rate(row['movements'], row['visibilities']), axis=1
)

# Normalise le movement_rate
df_score['movement_rate'] = scaler.fit_transform(df_score[['movement_rate']])

/var/folders/p9/_030_tzn0cx_x11mkmfz6w800000gn/T/ipykernel_20363/3528148233.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_score['movement_rate'] = df_videos.apply(
/var/folders/p9/_030_tzn0cx_x11mkmfz6w800000gn/T/ipykernel_20363/3528148233.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_score['movement_rate'] = scaler.fit_transform(df_score[['movement_rate']])

In [23]:
df_score

        nom   prénom  movement_rate
0   BETHOUX  camille        0.58554
1    MICHEL  Bernard        0.00000
2  BARTOZZI  Mathieu        1.00000

In [24]:
# Fonction pour calculer le score de débit de parole (speech rate)
def calculate_speech_score(speech_rate):
    speech_rate_normalized = scaler.fit_transform(speech_rate.values.reshape(-1, 1))
    return speech_rate_normalized

In [25]:
# Fonction pour calculer le score du ton en combinant pitch_mean et pitch_std
def calculate_tone_score(pitch_mean, pitch_std):

    # Normaliser pitch_mean et pitch_std
    pitch_mean_normalized = scaler.fit_transform(pitch_mean.values.reshape(-1, 1))
    pitch_std_normalized = scaler.fit_transform(pitch_std.values.reshape(-1, 1))

    # Calculer le score du ton avec des pondérations égales
    tone_score = 0.5 * pitch_mean_normalized + 0.5 * pitch_std_normalized

    return tone_score

In [26]:

# Appliquer la fonction pour calculer et normaliser le score de débit de parole (speech_rate)
df_score['speech_rate_score'] = calculate_speech_score(df_videos['speech_rate'])

# Appliquer la fonction pour calculer et normaliser le score de ton (combinaison pitch_mean et pitch_std)
if len(df_videos[['pitch_mean', 'pitch_std']]) > 1:
    df_score['tone_score'] = calculate_tone_score(df_videos['pitch_mean'], df_videos['pitch_std'])
else:
    # Si une seule valeur, on assigne un score de 0.5 par défaut
    df_score['tone_score'] = 0.5

/var/folders/p9/_030_tzn0cx_x11mkmfz6w800000gn/T/ipykernel_20363/2008321914.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_score['speech_rate_score'] = calculate_speech_score(df_videos['speech_rate'])
/var/folders/p9/_030_tzn0cx_x11mkmfz6w800000gn/T/ipykernel_20363/2008321914.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_score['tone_score'] = calculate_tone_score(df_videos['pitch_mean'], df_videos['pitch_std'])

In [31]:
# Calculer le score global de communication non verbale avec des pondérations
df_score['non_verbal_communication_score'] = (
    0.5 * df_score['movement_rate'] +
    0.3 * df_score['speech_rate_score'] +
    0.2 * df_score['tone_score']
)

# Calculer la moyenne des scores non verbaux
threshold = df_score['non_verbal_communication_score'].mean()

# Appliquer la moyenne comme seuil pour obtenir un score binaire (0 ou 1)
df_score['non_verbal_communication_binary'] = df_score['non_verbal_communication_score'].apply(
    lambda score: 1 if score >= threshold else 0
)

/var/folders/p9/_030_tzn0cx_x11mkmfz6w800000gn/T/ipykernel_20363/3711508450.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_score['non_verbal_communication_score'] = (
/var/folders/p9/_030_tzn0cx_x11mkmfz6w800000gn/T/ipykernel_20363/3711508450.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_score['non_verbal_communication_binary'] = df_score['non_verbal_communication_score'].apply(

In [32]:
df_score

,nom,prénom,movement_rate,speech_rate_score,tone_score,non_verbal_communication_score,non_verbal_communication_binary
0,BETHOUX,camille,0.58554,0.000000,0.732170,0.439204,0
1,MICHEL,Bernard,0.00000,0.379593,0.000000,0.113878,0
2,BARTOZZI,Mathieu,1.00000,1.000000,0.625407,0.925081,1

### Analyse et scoring du transcript

In [35]:
import spacy
from collections import defaultdict

# Charger le modèle de langue français de spaCy
nlp = spacy.load("fr_core_news_md")

In [51]:
import json

# Charger les mots-clés depuis le fichier JSON
with open('../data/keywords.json', 'r') as f:
    keywords = json.load(f)

In [67]:
#scoring de l'introduction
def score_introduction(transcript, keywords):
    # Vérifie si au moins un des mots-clés de justification est présent
    return 1 if any(kw in transcript.lower() for kw in keywords['justification']) else 0

In [71]:
# Scoring de la méthode STAR
def score_star(transcript, keywords):
    star_score = 0
    # Vérification des différentes étapes de la méthode STAR
    star_score += 1 if any(kw in transcript.lower() for kw in keywords['situation']) else 0
    star_score += 1 if any(kw in transcript.lower() for kw in keywords['task']) else 0
    star_score += 1 if any(kw in transcript.lower() for kw in keywords['action']) else 0
    star_score += 1 if any(kw in transcript.lower() for kw in keywords['result']) else 0
    return star_score

# Scoring de la personnalisation
def score_authenticity(transcript):
    # Liste d'expressions qui indiquent de la personnalisation ou des détails spécifiques
    authenticity_keywords = [
        "mon expérience", "dans mon projet", "lorsque j’ai travaillé sur",
        "dans cette entreprise", "ce projet m’a permis", "en travaillant avec", "j'ai pu observer"
    ]
    return 1 if any(kw in transcript.lower() for kw in authenticity_keywords) else 0

# Fonction pour calculer le score combiné
def calculate_combined_score(transcript, keywords):
    # Calcul du score STAR (avec pondération de 0.3)
    star_score = score_star(transcript, keywords) * 0.3

    # Calcul du score d'authenticité (avec pondération de 0.2)
    authenticity_score = score_authenticity(transcript) * 0.2

    # Calcul du score total combiné
    total_score = star_score + authenticity_score

    # Retourner le score combiné
    return total_score

# Appliquer la fonction à chaque transcript dans le DataFrame df_score
df_score['star_score'] = df_videos['transcript'].apply(lambda transcript: calculate_combined_score(transcript, keywords))

# Si tu veux convertir le score en binaire (0 ou 1) avec un seuil basé sur la moyenne :
threshold_combined = df_score['star_score'].mean()
df_score['star_score_binary'] = df_score['star_score'].apply(
    lambda score: 1 if score >= threshold_combined else 0
)

In [72]:
df_score['score_introduction'] = df_videos['transcript'].apply(lambda transcript: score_introduction(transcript, keywords))
df_score['score_star'] = df_videos['transcript'].apply(lambda transcript: score_introduction(transcript, keywords))

In [73]:
# Appliquer l'analyse et calculer le score global pour chaque transcript
df_score['transcript_score'] = df_videos['transcript'].apply(lambda transcript: calculate_total_score(transcript, keywords))

In [74]:
df_score

,nom,prénom,movement_rate,speech_rate_score,tone_score,non_verbal_communication_score,non_verbal_communication_binary,transcript_score,introduction_score,score_introduction,score_star,star_score,star_score_binary
0,BETHOUX,camille,0.58554,0.000000,0.732170,0.439204,0,0.225,0,0,0,0.9,1
1,MICHEL,Bernard,0.00000,0.379593,0.000000,0.113878,0,0.225,0,0,0,0.9,1
2,BARTOZZI,Mathieu,1.00000,1.000000,0.625407,0.925081,1,0.075,0,0,0,0.3,0